#!/bin/bash

echo "=== GitHub Secrets Setup for Vercel Deployment ==="
echo ""
echo "You need to add these secrets to your GitHub repository:"
echo "Repository Settings → Secrets and variables → Actions → Repository secrets"
echo ""
echo "1. VERCEL_TOKEN:"
echo "   Go to https://vercel.com/account/tokens"
echo "   Create a new token with appropriate permissions"
echo "   Copy the token value"
echo ""
echo "2. VERCEL_ORG_ID:"
echo "   team_rebTj3bpbQjCVd8eeHaIWhEk"
echo ""
echo "3. VERCEL_PROJECT_ID:"
echo "   prj_4fxnDCBeB2x7EazOrAtT3a6kwR6c"
echo ""
echo "After adding these secrets, your GitHub Actions workflow should work correctly."
echo ""
echo "To add secrets to GitHub:"
echo "1. Go to https://github.com/orcunbalcilar/auth-template/settings/secrets/actions"
echo "2. Click 'New repository secret'"
echo "3. Add each secret with the exact name and value shown above"
